# Generated by Django 4.2.30 on 2026-05-27 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='班级名称')),
                ('grade', models.CharField(max_length=50, verbose_name='年级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'class_group',
                'ordering': ['grade', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='签到码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course_start_time', models.DateTimeField(blank=True, null=True, verbose_name='课程开始时间')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否有效')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class', verbose_name='所属班级')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建教师')),
            ],
            options={
                'verbose_name': '签到码',
                'verbose_name_plural': '签到码',
                'db_table': 'attendance_attendancecode',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('status', models.CharField(choices=[('正常', '正常'), ('迟到', '迟到'), ('缺勤', '缺勤')], default='正常', max_length=20, verbose_name='签到状态')),
                ('attendance_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancecode', verbose_name='对应签到码')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='签到学生')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'db_table': 'attendance_attendancerecord',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'timestamp'], name='idx_student_timestamp')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'attendance_code'), name='uq_student_code'),
        ),
        migrations.AddIndex(
            model_name='attendancecode',
            index=models.Index(fields=['class_group', 'is_active'], name='idx_class_active'),
        ),
        migrations.AddIndex(
            model_name='attendancecode',
            index=models.Index(fields=['code', 'is_active'], name='idx_active_code'),
        ),
    ]
